// packages/solid/src/components/FieldArray.tsx
import type {
  FieldArrayPath,
  FieldPath,
  FieldValues,
  MaybeArray,
  ResponseData,
  ValidateFieldArray,
} from '@modular-forms/core';
import { handleLifecycle } from '@modular-forms/core';
import {
  batch,
  createEffect,
  createMemo,
  onCleanup as cleanup,
  untrack,
  type JSX,
} from 'solid-js';
import type { FieldArrayStore, FormStore } from '../types';
import { initializeFieldArrayStore } from '../utils';

/**
 * Value type of the field array props.
 */
export type FieldArrayProps<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData,
  TFieldName extends FieldPath<TFieldValues>,
  TFieldArrayName extends FieldArrayPath<TFieldValues>
> = {
  of: FormStore<TFieldValues, TResponseData, TFieldName, TFieldArrayName>;
  name: TFieldArrayName;
  children: (
    fieldArray: FieldArrayStore<TFieldValues, TFieldArrayName>
  ) => JSX.Element;
  validate?: MaybeArray<ValidateFieldArray<number[]>>;
  keepActive?: boolean;
  keepState?: boolean;
};

/**
 * Headless field array that provides reactive properties and state.
 */
export function FieldArray<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData,
  TFieldName extends FieldPath<TFieldValues>,
  TFieldArrayName extends FieldArrayPath<TFieldValues>
>(
  props: FieldArrayProps<
    TFieldValues,
    TResponseData,
    TFieldName,
    TFieldArrayName
  >
): JSX.Element {
  // Get store of specified field array
  const getFieldArray = createMemo(() =>
    initializeFieldArrayStore(props.of, props.name)
  );

  // Create lifecycle of field
  createEffect(() =>
    handleLifecycle(
      { batch, untrack, cleanup },
      { store: getFieldArray(), ...props }
    )
  );

  return <>{props.children(getFieldArray())}</>;
}

// packages/qwik/src/components/FieldArray.tsx
import type { QRL } from '@builder.io/qwik';
import type { JSX } from '@builder.io/qwik/jsx-runtime';
import type {
  FieldArrayPath,
  FieldArrayStore,
  FieldPath,
  FieldValues,
  FormStore,
  Maybe,
  MaybeArray,
  ResponseData,
  ValidateFieldArray,
} from '@modular-forms/shared';
import { getFieldArrayStore } from '@modular-forms/shared';
import { Lifecycle } from './Lifecycle';

/**
 * Value type of the field array props.
 */
export type FieldArrayProps<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData,
  TFieldName extends FieldPath<TFieldValues>,
  TFieldArrayName extends FieldArrayPath<TFieldValues>
> = {
  of: FormStore<TFieldValues, TResponseData, TFieldName, TFieldArrayName>;
  name: TFieldArrayName;
  children: (
    store: FieldArrayStore<TFieldValues, TFieldArrayName>
  ) => JSX.Element;
  validate?: Maybe<MaybeArray<QRL<ValidateFieldArray<number[]>>>>;
  keepActive?: Maybe<boolean>;
  keepState?: Maybe<boolean>;
};

/**
 * Headless field array that provides reactive properties and state.
 */
export function FieldArray<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData,
  TFieldName extends FieldPath<TFieldValues>,
  TFieldArrayName extends FieldArrayPath<TFieldValues>
>({
  children,
  name,
  ...props
}: FieldArrayProps<
  TFieldValues,
  TResponseData,
  TFieldName,
  TFieldArrayName
>): JSX.Element {
  // Get store of specified field
  const fieldArray = getFieldArrayStore(props.of, name)!;

  return (
    <Lifecycle key={name} store={fieldArray} {...props}>
      {children(fieldArray)}
    </Lifecycle>
  );
}
