// playgrounds/qwik/src/components/Head.tsx
import { component$ } from '@builder.io/qwik';
import { useDocumentHead, useLocation } from '@builder.io/qwik-city';

/**
 * Head with title, meta, link and script elements.
 */
export const Head = component$(() => {
  const documentHead = useDocumentHead();
  const location = useLocation();

  return (
    <head>
      <title>{`${documentHead.title} | Modular Forms`}</title>

      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <link rel="manifest" href="/manifest.json" />
      <link rel="canonical" href={location.url.href} />
      <link rel="icon" href="/favicon.ico" />

      {documentHead.meta.map((meta) => (
        <meta {...meta} />
      ))}

      {documentHead.links.map((link) => (
        <link {...link} />
      ))}

      {documentHead.styles.map((style) => (
        <style {...style.props} dangerouslySetInnerHTML={style.style} />
      ))}

      <script
        // Add "dark" class for theming before browser has chance to paint to
        // prevent screen from flashing between two color modes
        dangerouslySetInnerHTML={`
          if (!window.matchMedia('(prefers-color-scheme: light)').matches) {
            document.documentElement.classList.add('dark');
          }
        `}
      />
    </head>
  );
});

// playgrounds/solid/src/components/Head.tsx
import { Head as SolidHead, Meta, Title } from 'solid-start';

/**
 * Head with title, meta, link and script elements.
 */
export function Head() {
  return (
    <SolidHead>
      <Title>Modular Forms Playground</Title>
      <Meta charset="utf-8" />
      <Meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <script
        // If necessary, add "dark" class for theming before browser has
        // chance to paint to prevent screen from flashing between two
        // color modes
        innerHTML={`
          const theme = localStorage.getItem('theme');
          const { classList } = document.documentElement;
          if (
            theme === 'dark' ||
            (!theme &&
              window.matchMedia('(prefers-color-scheme: dark)').matches)
          ) {
            classList.add('dark');
          } else {
            classList.remove('dark');
          }
        `}
      />
    </SolidHead>
  );
}
