// packages/qwik/src/components/Form.tsx
import type { QwikSubmitEvent } from '@builder.io/qwik';
import type { ActionStore } from '@builder.io/qwik-city';
import type { JSX } from '@builder.io/qwik/jsx-runtime';
import { FormError } from '../exceptions';
import { getValues, setResponse, validate } from '../methods';
import type {
  FieldValues,
  FormActionStore,
  FormStore,
  Maybe,
  MaybePromise,
  MaybeQRL,
  PartialValues,
  ResponseData,
} from '../types';
import { setErrorResponse, setFieldErrors } from '../utils';

/**
 * Function type to handle the submission of the form.
 */
export type SubmitHandler<TFieldValues extends FieldValues> = MaybeQRL<
  (
    values: TFieldValues,
    event: QwikSubmitEvent<HTMLFormElement>
  ) => MaybePromise<any>
>;

/**
 * Value type of the form properties.
 */
export type FormProps<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData
> = {
  // Custom props
  of: FormStore<TFieldValues, TResponseData>;
  action?: Maybe<
    ActionStore<
      FormActionStore<TFieldValues, TResponseData>,
      PartialValues<TFieldValues>,
      true
    >
  >;
  onSubmit$?: Maybe<SubmitHandler<TFieldValues>>;
  responseDuration?: Maybe<number>;
  keepResponse?: Maybe<boolean>;
  shouldActive?: Maybe<boolean>;
  shouldTouched?: Maybe<boolean>;
  shouldDirty?: Maybe<boolean>;
  shouldFocus?: Maybe<boolean>;
  reloadDocument?: Maybe<boolean>;

  // HTML props
  id?: Maybe<string>;
  class?: Maybe<string>;
  autoComplete?: Maybe<'on' | 'off'>;
  encType?: Maybe<'application/x-www-form-urlencoded' | 'multipart/form-data'>;
  name?: Maybe<string>;
  children: any;
};

/**
 * Form element that takes care of validation and simplifies submission.
 */
export function Form<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData
>({
  of: form,
  action,
  onSubmit$,
  responseDuration: duration,
  keepResponse,
  shouldActive,
  shouldTouched,
  shouldDirty,
  shouldFocus,
  reloadDocument,
  children,
  ...formProps
}: FormProps<TFieldValues, TResponseData>): JSX.Element {
  // Destructure form props
  const { encType } = formProps;

  // Create options object
  const options = {
    duration,
    shouldActive,
    shouldTouched,
    shouldDirty,
    shouldFocus,
  };

  return (
    <form
      {...formProps}
      method="post"
      action={action?.actionPath}
      preventdefault:submit={!reloadDocument}
      noValidate
      ref={(element: Element) => {
        form.element = element as HTMLFormElement;
      }}
      onSubmit$={async (event: QwikSubmitEvent<HTMLFormElement>, element) => {
        // Reset response if it is not to be kept
        if (!keepResponse) {
          form.response = {};
        }

        // Increase submit count and set submitted and submitting to "true"
        form.submitCount++;
        form.submitted = true;
        form.submitting = true;

        // Try to run submit actions if form is valid
        try {
          if (await validate(form, options)) {
            // Get current values of form
            const values = getValues(form, options);

            // Run submit actions of form
            const [actionResult] = await Promise.all([
              !reloadDocument
                ? action?.submit(encType ? new FormData(element) : values)
                : undefined,
              // eslint-disable-next-line qwik/valid-lexical-scope
              onSubmit$?.(values as TFieldValues, event),
            ]);

            // Set form action result if necessary
            if (actionResult?.value) {
              const { errors, response } = actionResult.value;
              setFieldErrors(form, errors, { ...options, shouldFocus: false });
              if (Object.keys(response).length) {
                setResponse(form, response, options);
              } else {
                setErrorResponse(form, errors, options);
              }
            }
          }

          // If an error occurred, set error to fields and response
        } catch (error: any) {
          if (error instanceof FormError) {
            setFieldErrors(form, error.errors, {
              ...options,
              shouldFocus: false,
            });
          }
          if (!(error instanceof FormError) || error.message) {
            setResponse(
              form,
              {
                status: 'error',
                message: error?.message || 'An unknown error has occurred.',
              },
              options
            );
          }

          // Finally set submitting back to "false"
        } finally {
          form.submitting = false;
        }
      }}
    >
      {children}
    </form>
  );
}

// packages/solid/src/components/Form.tsx
import { batch, type JSX, splitProps } from 'solid-js';
import { FormError } from '../exceptions';
import { getValues, setError, setResponse, validate } from '../methods';
import type {
  FieldArrayPath,
  FieldPath,
  FieldValues,
  FormStore,
  Maybe,
  MaybePromise,
  ResponseData,
} from '../types';

/**
 * Value type of the submit event object.
 */
export type SubmitEvent = Event & {
  submitter: HTMLElement;
} & {
  currentTarget: HTMLFormElement;
  target: Element;
};

/**
 * Function type to handle the submission of the form.
 */
export type SubmitHandler<TFieldValues extends FieldValues> = (
  values: TFieldValues,
  event: SubmitEvent
) => MaybePromise<any>;

/**
 * Value type of the form properties.
 */
export type FormProps<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData
> = Omit<JSX.FormHTMLAttributes<HTMLFormElement>, 'onSubmit'> & {
  of: FormStore<TFieldValues, TResponseData>;
  onSubmit: SubmitHandler<TFieldValues>;
  responseDuration?: Maybe<number>;
  keepResponse?: Maybe<boolean>;
  shouldActive?: Maybe<boolean>;
  shouldTouched?: Maybe<boolean>;
  shouldDirty?: Maybe<boolean>;
  shouldFocus?: Maybe<boolean>;
  children: JSX.Element;
};

/**
 * HTML form element that simplifies form submission and disables the browser's
 * default form validation.
 */
export function Form<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData
>(props: FormProps<TFieldValues, TResponseData>): JSX.Element {
  // Split props between local, options and other
  const [options, other] = splitProps(props, [
    'keepResponse',
    'shouldActive',
    'shouldTouched',
    'shouldDirty',
    'shouldFocus',
  ]);

  return (
    <form
      novalidate
      {...other}
      ref={props.of.internal.element.set}
      onSubmit={async (event: SubmitEvent) => {
        // Prevent default behavior of browser
        event.preventDefault();

        // Destructure props
        // eslint-disable-next-line solid/reactivity
        const { of: form, onSubmit, responseDuration: duration } = props;

        batch(() => {
          // Reset response if it is not to be kept
          if (!options.keepResponse) {
            form.internal.response.set({});
          }

          // Increase submit count and set submitted and submitting to "true"
          form.internal.submitCount.set((count) => count + 1);
          form.internal.submitted.set(true);
          form.internal.submitting.set(true);
        });

        // Try to run submit actions if form is valid
        try {
          if (await validate(form, options)) {
            await onSubmit(getValues(form, options) as TFieldValues, event);
          }

          // If an error occurred, set error to fields and response
        } catch (error: any) {
          batch(() => {
            if (error instanceof FormError) {
              (
                Object.entries(error.errors) as [
                  FieldPath<TFieldValues> | FieldArrayPath<TFieldValues>,
                  Maybe<string>
                ][]
              ).forEach(([name, error]) => {
                if (error) {
                  setError(form, name, error, {
                    ...options,
                    shouldFocus: false,
                  });
                }
              });
            }
            if (!(error instanceof FormError) || error.message) {
              setResponse(
                form,
                {
                  status: 'error',
                  message: error?.message || 'An unknown error has occurred.',
                },
                { duration }
              );
            }
          });

          // Finally set submitting back to "false"
        } finally {
          form.internal.submitting.set(false);
        }
      }}
    />
  );
}
