// playgrounds/preact/src/components/ButtonGroup.tsx
import clsx from 'clsx';
import { ComponentChildren } from 'preact';

type ButtonGroupProps = {
  children: ComponentChildren;
  class?: string;
};

/**
 * Button group displays multiple related actions side-by-side and helps with
 * arrangement and spacing.
 */
export function ButtonGroup(props: ButtonGroupProps) {
  return (
    <div
      {...props}
      class={clsx('flex flex-wrap gap-6 px-8 lg:gap-8 lg:px-10', props.class)}
    />
  );
}

// packages/website/src/components/ButtonGroup.tsx
import clsx from 'clsx';
import { JSX } from 'solid-js';

interface ButtonGroupProps {
  class?: string;
  children: JSX.Element;
}

/**
 * Button group displays multiple related actions side-by-side and helps with
 * arrangement and spacing.
 */
export function ButtonGroup(props: ButtonGroupProps) {
  return (
    <div
      class={clsx('flex flex-wrap gap-6 px-8 lg:gap-8 lg:px-10', props.class)}
    >
      {props.children}
    </div>
  );
}
